apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base-cron-job/

namePrefix: best-practice-
namespace: development

images:
  - name: IMAGE_NAME
    newName: ubuntu
    newTag: "20.04"

commonLabels:
  app.kubernetes.io/name: BestPracticeDeployment
  app.kubernetes.io/version: "0.0.1"
  app.kubernetes.io/component: Web
  app.kubernetes.io/part-of: BestPractice
  app.kubernetes.io/managed-by: Pipeline

patches:
  - target:
      kind: CronJob
      name: job
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/resources/requests
        value:
          cpu: '120m'
          memory: '150Mi'
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/resources/limits
        value:
          cpu: '300m'
          memory: '300Mi'
  - target:
      kind: CronJob
      name: job
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/command
        value:
          - sleep 300
